# Generated by Django 3.2.3 on 2021-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('Key', models.AutoField(primary_key=True, serialize=False)),
                ('CarouselTittle', models.CharField(max_length=100)),
                ('CarouselDesc', models.CharField(max_length=200)),
                ('Carouselimage', models.FileField(blank=True, upload_to='programs/carousel/')),
            ],
        ),
    ]
