# Generated by Django 3.2.3 on 2021-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('Key', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=100)),
                ('EventDisc', models.CharField(max_length=200)),
                ('EventDate', models.DateField()),
                ('EventLink', models.CharField(max_length=400)),
            ],
        ),
    ]
