# Generated by Django 3.2.3 on 2021-05-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('ProgramID', models.AutoField(primary_key=True, serialize=False)),
                ('ProgramName', models.CharField(max_length=100)),
                ('ProgramDesc', models.CharField(max_length=1000)),
                ('ProgramDate', models.DateField()),
                ('ProgramImageCount', models.IntegerField()),
            ],
        ),
    ]
