# Generated by Django 3.2.3 on 2021-06-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('InnovationID', models.AutoField(primary_key=True, serialize=False)),
                ('InnovationName', models.CharField(max_length=100)),
                ('InnovationShortDesc', models.CharField(max_length=150)),
                ('InnovationDesc', models.CharField(max_length=2000)),
                ('InnovationLink', models.CharField(default='#', max_length=300)),
                ('InnovationYBLink', models.CharField(max_length=200)),
                ('InnovationDate', models.DateField()),
                ('image', models.FileField(blank=True, upload_to='programs/innovations/')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='programs/innovations/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagges', to='Innovation.innovation')),
            ],
        ),
    ]
