# Generated by Django 3.2.3 on 2021-06-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovativeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='programs/innovations/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagges', to='Innovation.innovation')),
            ],
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
