# Generated by Django 3.2.3 on 2021-06-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation', '0002_auto_20210603_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='InnovationYBLink',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
