# Generated by Django 3.2.3 on 2021-06-03 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Innovation', '0003_alter_innovation_innovationyblink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovativeimages',
            name='post',
        ),
        migrations.AddField(
            model_name='innovativeimages',
            name='InoIMG',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inoimages', to='Innovation.innovation'),
        ),
    ]
